// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LedTape.proto

package org.ndbs.aled.client.api;

public final class LedTapeOuterClass {
  private LedTapeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LedTapeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LedTape)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    java.util.List<LedTapeOuterClass.LedTape.Diode> 
        getDiodesList();
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    LedTapeOuterClass.LedTape.Diode getDiodes(int index);
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    int getDiodesCount();
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    java.util.List<? extends LedTapeOuterClass.LedTape.DiodeOrBuilder> 
        getDiodesOrBuilderList();
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    LedTapeOuterClass.LedTape.DiodeOrBuilder getDiodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code LedTape}
   */
  public  static final class LedTape extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LedTape)
      LedTapeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LedTape.newBuilder() to construct.
    private LedTape(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LedTape() {
      diodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LedTape(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                diodes_ = new java.util.ArrayList<LedTapeOuterClass.LedTape.Diode>();
                mutable_bitField0_ |= 0x00000001;
              }
              diodes_.add(
                  input.readMessage(LedTapeOuterClass.LedTape.Diode.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          diodes_ = java.util.Collections.unmodifiableList(diodes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LedTapeOuterClass.internal_static_LedTape_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LedTapeOuterClass.internal_static_LedTape_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LedTapeOuterClass.LedTape.class, LedTapeOuterClass.LedTape.Builder.class);
    }

    public interface DiodeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:LedTape.Diode)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       */
      int getId();

      /**
       * <code>int32 r = 2;</code>
       */
      int getR();

      /**
       * <code>int32 g = 3;</code>
       */
      int getG();

      /**
       * <code>int32 b = 4;</code>
       */
      int getB();
    }
    /**
     * Protobuf type {@code LedTape.Diode}
     */
    public  static final class Diode extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:LedTape.Diode)
        DiodeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Diode.newBuilder() to construct.
      private Diode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Diode() {
        id_ = 0;
        r_ = 0;
        g_ = 0;
        b_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Diode(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 16: {

                r_ = input.readInt32();
                break;
              }
              case 24: {

                g_ = input.readInt32();
                break;
              }
              case 32: {

                b_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LedTapeOuterClass.internal_static_LedTape_Diode_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LedTapeOuterClass.internal_static_LedTape_Diode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LedTapeOuterClass.LedTape.Diode.class, LedTapeOuterClass.LedTape.Diode.Builder.class);
      }

      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int R_FIELD_NUMBER = 2;
      private int r_;
      /**
       * <code>int32 r = 2;</code>
       */
      public int getR() {
        return r_;
      }

      public static final int G_FIELD_NUMBER = 3;
      private int g_;
      /**
       * <code>int32 g = 3;</code>
       */
      public int getG() {
        return g_;
      }

      public static final int B_FIELD_NUMBER = 4;
      private int b_;
      /**
       * <code>int32 b = 4;</code>
       */
      public int getB() {
        return b_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        if (r_ != 0) {
          output.writeInt32(2, r_);
        }
        if (g_ != 0) {
          output.writeInt32(3, g_);
        }
        if (b_ != 0) {
          output.writeInt32(4, b_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (r_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, r_);
        }
        if (g_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, g_);
        }
        if (b_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, b_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof LedTapeOuterClass.LedTape.Diode)) {
          return super.equals(obj);
        }
        LedTapeOuterClass.LedTape.Diode other = (LedTapeOuterClass.LedTape.Diode) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && (getR()
            == other.getR());
        result = result && (getG()
            == other.getG());
        result = result && (getB()
            == other.getB());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        hash = (37 * hash) + R_FIELD_NUMBER;
        hash = (53 * hash) + getR();
        hash = (37 * hash) + G_FIELD_NUMBER;
        hash = (53 * hash) + getG();
        hash = (37 * hash) + B_FIELD_NUMBER;
        hash = (53 * hash) + getB();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static LedTapeOuterClass.LedTape.Diode parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static LedTapeOuterClass.LedTape.Diode parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static LedTapeOuterClass.LedTape.Diode parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(LedTapeOuterClass.LedTape.Diode prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code LedTape.Diode}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:LedTape.Diode)
          LedTapeOuterClass.LedTape.DiodeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return LedTapeOuterClass.internal_static_LedTape_Diode_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return LedTapeOuterClass.internal_static_LedTape_Diode_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  LedTapeOuterClass.LedTape.Diode.class, LedTapeOuterClass.LedTape.Diode.Builder.class);
        }

        // Construct using LedTapeOuterClass.LedTape.Diode.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0;

          r_ = 0;

          g_ = 0;

          b_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return LedTapeOuterClass.internal_static_LedTape_Diode_descriptor;
        }

        @java.lang.Override
        public LedTapeOuterClass.LedTape.Diode getDefaultInstanceForType() {
          return LedTapeOuterClass.LedTape.Diode.getDefaultInstance();
        }

        @java.lang.Override
        public LedTapeOuterClass.LedTape.Diode build() {
          LedTapeOuterClass.LedTape.Diode result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public LedTapeOuterClass.LedTape.Diode buildPartial() {
          LedTapeOuterClass.LedTape.Diode result = new LedTapeOuterClass.LedTape.Diode(this);
          result.id_ = id_;
          result.r_ = r_;
          result.g_ = g_;
          result.b_ = b_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof LedTapeOuterClass.LedTape.Diode) {
            return mergeFrom((LedTapeOuterClass.LedTape.Diode)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(LedTapeOuterClass.LedTape.Diode other) {
          if (other == LedTapeOuterClass.LedTape.Diode.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (other.getR() != 0) {
            setR(other.getR());
          }
          if (other.getG() != 0) {
            setG(other.getG());
          }
          if (other.getB() != 0) {
            setB(other.getB());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          LedTapeOuterClass.LedTape.Diode parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (LedTapeOuterClass.LedTape.Diode) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private int r_ ;
        /**
         * <code>int32 r = 2;</code>
         */
        public int getR() {
          return r_;
        }
        /**
         * <code>int32 r = 2;</code>
         */
        public Builder setR(int value) {
          
          r_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 r = 2;</code>
         */
        public Builder clearR() {
          
          r_ = 0;
          onChanged();
          return this;
        }

        private int g_ ;
        /**
         * <code>int32 g = 3;</code>
         */
        public int getG() {
          return g_;
        }
        /**
         * <code>int32 g = 3;</code>
         */
        public Builder setG(int value) {
          
          g_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 g = 3;</code>
         */
        public Builder clearG() {
          
          g_ = 0;
          onChanged();
          return this;
        }

        private int b_ ;
        /**
         * <code>int32 b = 4;</code>
         */
        public int getB() {
          return b_;
        }
        /**
         * <code>int32 b = 4;</code>
         */
        public Builder setB(int value) {
          
          b_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 b = 4;</code>
         */
        public Builder clearB() {
          
          b_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:LedTape.Diode)
      }

      // @@protoc_insertion_point(class_scope:LedTape.Diode)
      private static final LedTapeOuterClass.LedTape.Diode DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new LedTapeOuterClass.LedTape.Diode();
      }

      public static LedTapeOuterClass.LedTape.Diode getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Diode>
          PARSER = new com.google.protobuf.AbstractParser<Diode>() {
        @java.lang.Override
        public Diode parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Diode(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Diode> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Diode> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public LedTapeOuterClass.LedTape.Diode getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int DIODES_FIELD_NUMBER = 1;
    private java.util.List<LedTapeOuterClass.LedTape.Diode> diodes_;
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    public java.util.List<LedTapeOuterClass.LedTape.Diode> getDiodesList() {
      return diodes_;
    }
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    public java.util.List<? extends LedTapeOuterClass.LedTape.DiodeOrBuilder> 
        getDiodesOrBuilderList() {
      return diodes_;
    }
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    public int getDiodesCount() {
      return diodes_.size();
    }
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    public LedTapeOuterClass.LedTape.Diode getDiodes(int index) {
      return diodes_.get(index);
    }
    /**
     * <code>repeated .LedTape.Diode diodes = 1;</code>
     */
    public LedTapeOuterClass.LedTape.DiodeOrBuilder getDiodesOrBuilder(
        int index) {
      return diodes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < diodes_.size(); i++) {
        output.writeMessage(1, diodes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < diodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, diodes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LedTapeOuterClass.LedTape)) {
        return super.equals(obj);
      }
      LedTapeOuterClass.LedTape other = (LedTapeOuterClass.LedTape) obj;

      boolean result = true;
      result = result && getDiodesList()
          .equals(other.getDiodesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDiodesCount() > 0) {
        hash = (37 * hash) + DIODES_FIELD_NUMBER;
        hash = (53 * hash) + getDiodesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LedTapeOuterClass.LedTape parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LedTapeOuterClass.LedTape parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LedTapeOuterClass.LedTape parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LedTapeOuterClass.LedTape parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LedTapeOuterClass.LedTape parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LedTapeOuterClass.LedTape parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LedTapeOuterClass.LedTape prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LedTape}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LedTape)
        LedTapeOuterClass.LedTapeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LedTapeOuterClass.internal_static_LedTape_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LedTapeOuterClass.internal_static_LedTape_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LedTapeOuterClass.LedTape.class, LedTapeOuterClass.LedTape.Builder.class);
      }

      // Construct using LedTapeOuterClass.LedTape.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDiodesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (diodesBuilder_ == null) {
          diodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          diodesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LedTapeOuterClass.internal_static_LedTape_descriptor;
      }

      @java.lang.Override
      public LedTapeOuterClass.LedTape getDefaultInstanceForType() {
        return LedTapeOuterClass.LedTape.getDefaultInstance();
      }

      @java.lang.Override
      public LedTapeOuterClass.LedTape build() {
        LedTapeOuterClass.LedTape result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LedTapeOuterClass.LedTape buildPartial() {
        LedTapeOuterClass.LedTape result = new LedTapeOuterClass.LedTape(this);
        int from_bitField0_ = bitField0_;
        if (diodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            diodes_ = java.util.Collections.unmodifiableList(diodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.diodes_ = diodes_;
        } else {
          result.diodes_ = diodesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LedTapeOuterClass.LedTape) {
          return mergeFrom((LedTapeOuterClass.LedTape)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LedTapeOuterClass.LedTape other) {
        if (other == LedTapeOuterClass.LedTape.getDefaultInstance()) return this;
        if (diodesBuilder_ == null) {
          if (!other.diodes_.isEmpty()) {
            if (diodes_.isEmpty()) {
              diodes_ = other.diodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDiodesIsMutable();
              diodes_.addAll(other.diodes_);
            }
            onChanged();
          }
        } else {
          if (!other.diodes_.isEmpty()) {
            if (diodesBuilder_.isEmpty()) {
              diodesBuilder_.dispose();
              diodesBuilder_ = null;
              diodes_ = other.diodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              diodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDiodesFieldBuilder() : null;
            } else {
              diodesBuilder_.addAllMessages(other.diodes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LedTapeOuterClass.LedTape parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LedTapeOuterClass.LedTape) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<LedTapeOuterClass.LedTape.Diode> diodes_ =
        java.util.Collections.emptyList();
      private void ensureDiodesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          diodes_ = new java.util.ArrayList<LedTapeOuterClass.LedTape.Diode>(diodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          LedTapeOuterClass.LedTape.Diode, LedTapeOuterClass.LedTape.Diode.Builder, LedTapeOuterClass.LedTape.DiodeOrBuilder> diodesBuilder_;

      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public java.util.List<LedTapeOuterClass.LedTape.Diode> getDiodesList() {
        if (diodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(diodes_);
        } else {
          return diodesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public int getDiodesCount() {
        if (diodesBuilder_ == null) {
          return diodes_.size();
        } else {
          return diodesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public LedTapeOuterClass.LedTape.Diode getDiodes(int index) {
        if (diodesBuilder_ == null) {
          return diodes_.get(index);
        } else {
          return diodesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder setDiodes(
          int index, LedTapeOuterClass.LedTape.Diode value) {
        if (diodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDiodesIsMutable();
          diodes_.set(index, value);
          onChanged();
        } else {
          diodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder setDiodes(
          int index, LedTapeOuterClass.LedTape.Diode.Builder builderForValue) {
        if (diodesBuilder_ == null) {
          ensureDiodesIsMutable();
          diodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          diodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder addDiodes(LedTapeOuterClass.LedTape.Diode value) {
        if (diodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDiodesIsMutable();
          diodes_.add(value);
          onChanged();
        } else {
          diodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder addDiodes(
          int index, LedTapeOuterClass.LedTape.Diode value) {
        if (diodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDiodesIsMutable();
          diodes_.add(index, value);
          onChanged();
        } else {
          diodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder addDiodes(
          LedTapeOuterClass.LedTape.Diode.Builder builderForValue) {
        if (diodesBuilder_ == null) {
          ensureDiodesIsMutable();
          diodes_.add(builderForValue.build());
          onChanged();
        } else {
          diodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder addDiodes(
          int index, LedTapeOuterClass.LedTape.Diode.Builder builderForValue) {
        if (diodesBuilder_ == null) {
          ensureDiodesIsMutable();
          diodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          diodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder addAllDiodes(
          java.lang.Iterable<? extends LedTapeOuterClass.LedTape.Diode> values) {
        if (diodesBuilder_ == null) {
          ensureDiodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, diodes_);
          onChanged();
        } else {
          diodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder clearDiodes() {
        if (diodesBuilder_ == null) {
          diodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          diodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public Builder removeDiodes(int index) {
        if (diodesBuilder_ == null) {
          ensureDiodesIsMutable();
          diodes_.remove(index);
          onChanged();
        } else {
          diodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public LedTapeOuterClass.LedTape.Diode.Builder getDiodesBuilder(
          int index) {
        return getDiodesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public LedTapeOuterClass.LedTape.DiodeOrBuilder getDiodesOrBuilder(
          int index) {
        if (diodesBuilder_ == null) {
          return diodes_.get(index);  } else {
          return diodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public java.util.List<? extends LedTapeOuterClass.LedTape.DiodeOrBuilder> 
           getDiodesOrBuilderList() {
        if (diodesBuilder_ != null) {
          return diodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(diodes_);
        }
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public LedTapeOuterClass.LedTape.Diode.Builder addDiodesBuilder() {
        return getDiodesFieldBuilder().addBuilder(
            LedTapeOuterClass.LedTape.Diode.getDefaultInstance());
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public LedTapeOuterClass.LedTape.Diode.Builder addDiodesBuilder(
          int index) {
        return getDiodesFieldBuilder().addBuilder(
            index, LedTapeOuterClass.LedTape.Diode.getDefaultInstance());
      }
      /**
       * <code>repeated .LedTape.Diode diodes = 1;</code>
       */
      public java.util.List<LedTapeOuterClass.LedTape.Diode.Builder> 
           getDiodesBuilderList() {
        return getDiodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          LedTapeOuterClass.LedTape.Diode, LedTapeOuterClass.LedTape.Diode.Builder, LedTapeOuterClass.LedTape.DiodeOrBuilder> 
          getDiodesFieldBuilder() {
        if (diodesBuilder_ == null) {
          diodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              LedTapeOuterClass.LedTape.Diode, LedTapeOuterClass.LedTape.Diode.Builder, LedTapeOuterClass.LedTape.DiodeOrBuilder>(
                  diodes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          diodes_ = null;
        }
        return diodesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LedTape)
    }

    // @@protoc_insertion_point(class_scope:LedTape)
    private static final LedTapeOuterClass.LedTape DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LedTapeOuterClass.LedTape();
    }

    public static LedTapeOuterClass.LedTape getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LedTape>
        PARSER = new com.google.protobuf.AbstractParser<LedTape>() {
      @java.lang.Override
      public LedTape parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LedTape(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LedTape> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LedTape> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LedTapeOuterClass.LedTape getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LedTape_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LedTape_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LedTape_Diode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LedTape_Diode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rLedTape.proto\"_\n\007LedTape\022\036\n\006diodes\030\001 \003" +
      "(\0132\016.LedTape.Diode\0324\n\005Diode\022\n\n\002id\030\001 \001(\005\022" +
      "\t\n\001r\030\002 \001(\005\022\t\n\001g\030\003 \001(\005\022\t\n\001b\030\004 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LedTape_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LedTape_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LedTape_descriptor,
        new java.lang.String[] { "Diodes", });
    internal_static_LedTape_Diode_descriptor =
      internal_static_LedTape_descriptor.getNestedTypes().get(0);
    internal_static_LedTape_Diode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LedTape_Diode_descriptor,
        new java.lang.String[] { "Id", "R", "G", "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
